spring:
  application:
    name: instazoo
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#For Docker
#  datasource:
#    url: jdbc:postgresql://db:5432/postgres
#    username: admin
#    password: root

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
