version: '3.8'

services:
  springbootapp:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

volumes:
  postgresql: { }

networks:
  backend: { }